application: band9u
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "6h"

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 5
  min_pending_latency: 15s
  max_pending_latency: automatic
  max_concurrent_requests: 50

libraries:
- name: django
  version: 1.5

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.less$
- ^(\..*)
- ^(/)?bin/.*
- ^(/)?etc/.*
- ^(/)?tools/.*
- ^(/)?apps/.*/tests/.*
- ^(/)?models/tests/.*

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:

- url: /favicon\.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon\.ico
  secure: always

- url: /images
  static_dir: media/images
  secure: always

- url: /fonts/(.*\.woff)
  mime_type: application/x-font-woff
  static_files: media/fonts/\1
  upload: media/fonts/(.*\.woff)

- url: /fonts/(.*\.svg)
  mime_type: image/svg+xml
  static_files: media/fonts/\1
  upload: media/fonts/(.*\.svg)

- url: /css
  static_dir: media/css
  secure: always

- url: /js
  static_dir: media/js
  secure: always

- url: /html
  static_dir: media/html
  secure: always

- url: /.*
  script: main.app
  secure: always
